asp.net/estudo02 - net-5/10 - asp-net-entity-PartialView/src/ApplicationMVC/Controllers/EstadosController.cs
using ApplicationBusiness.ParametrosModels;
using ApplicationInfra;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ApplicationMVC.Controllers
{
    [Authorize]
    public class EstadosController : Controller
    {
        private readonly Contexto _context;

        public EstadosController(Contexto context)
        {
            _context = context;
        }

        // GET: Estados
        public async Task<IActionResult> Index(string OrdenaParm)
        {
            ViewBag.IDOrdenaParm = "ID";
            ViewBag.NameOrdenaParm = "nome";
            ViewBag.SiglaOrdenaParm = "sigla";
            ViewBag.PaisOrdenaParm = "pais";

            var contexto = _context.Estado.Include(e => e.Pais);
            
            List<Estado> estado;

            switch (OrdenaParm)
            {
                case "ID":
                    estado = await contexto.OrderBy(s => s.ID).ToListAsync();
                    break;
                case "nome":
                    estado = await contexto.OrderBy(s => s.Nome).ToListAsync();
                    break;
                case "sigla":
                    estado = await contexto.OrderBy(s => s.Sigla).ToListAsync();
                    break;
                case "pais":
                    estado = await contexto.OrderBy(s => s.Pais.Nome).ToListAsync();
                    break;
                default:
                    estado = await contexto.OrderBy(s => s.Nome).ToListAsync();
                    break;
            }

            //var contexto = _context.Estado.Include(e => e.Pais);
            //return View(await contexto.OrderBy(s => s.Nome).ToListAsync());
            return View(estado);
        }

        // GET: Estados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estado = await _context.Estado
                .Include(e => e.Pais)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (estado == null)
            {
                return NotFound();
            }

            return View(estado);
        }

        // GET: Estados/Create
        public IActionResult Create()
        {
            ViewData["PaisID"] = new SelectList(_context.Pais, "ID", "Nome");
            return View();
        }

        // POST: Estados/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Nome,Sigla,PaisID")] Estado estado)
        {
            if (ModelState.IsValid)
            {
                _context.Add(estado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PaisID"] = new SelectList(_context.Pais, "ID", "Nome", estado.PaisID);                               
            return View(estado);
        }

        // GET: Estados/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estado = await _context.Estado.FindAsync(id);
            if (estado == null)
            {
                return NotFound();
            }
            ViewData["PaisID"] = new SelectList(_context.Pais, "ID", "Nome", estado.PaisID);
            return View(estado);
        }

        // POST: Estados/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Nome,Sigla,PaisID")] Estado estado)
        {
            if (id != estado.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstadoExists(estado.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PaisID"] = new SelectList(_context.Pais, "ID", "Nome", estado.PaisID);
            return View(estado);
        }

        // GET: Estados/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estado = await _context.Estado
                .Include(e => e.Pais)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (estado == null)
            {
                return NotFound();
            }

            return View(estado);
        }

        // POST: Estados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var estado = await _context.Estado.FindAsync(id);
            _context.Estado.Remove(estado);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstadoExists(int id)
        {
            return _context.Estado.Any(e => e.ID == id);
        }
    }
}

asp.net/estudo02 - net-5/10 - asp-net-entity-PartialView/src/ApplicationMVC/Controllers/PaisesController.cs
using ApplicationBusiness.ParametrosModels;
using ApplicationInfra;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ApplicationMVC.Controllers
{
    [Authorize]
    public class PaisesController : Controller
    {
        private readonly Contexto _context;

        public PaisesController(Contexto context)
        {
            _context = context;
        }

        // GET: Paises
        public async Task<IActionResult> Index(string OrdenaParm)
        {
            ViewBag.NameOrdenaParm = "nome";
            ViewBag.SiglaOrdenaParm = "sigla";
            
            var contexto = _context.Pais.Include(e => e.Estados);

            List<Pais> pais;

            switch (OrdenaParm)
            {
                case "nome":
                    pais = await contexto.OrderBy(s => s.Nome).ToListAsync();
                    break;
                case "sigla":
                    pais = await contexto.OrderBy(s => s.Sigla).ToListAsync();
                    break;
                default:
                    pais = await contexto.OrderBy(s => s.Nome).ToListAsync();
                    break;
            }
            //return View(await _context.Pais.OrderBy(s => s.Nome).ToListAsync());
            return View(pais);
        }

        // GET: Paises/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pais = await _context.Pais
                .FirstOrDefaultAsync(m => m.ID == id);
            if (pais == null)
            {
                return NotFound();
            }

            return View(pais);
        }

        // GET: Paises/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Paises/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Nome,Sigla")] Pais pais)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pais);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pais);
        }

        // GET: Paises/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pais = await _context.Pais.FindAsync(id);
            if (pais == null)
            {
                return NotFound();
            }
            return View(pais);
        }

        // POST: Paises/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Nome,Sigla")] Pais pais)
        {
            if (id != pais.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pais);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaisExists(pais.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pais);
        }

        // GET: Paises/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pais = await _context.Pais
                .FirstOrDefaultAsync(m => m.ID == id);
            if (pais == null)
            {
                return NotFound();
            }

            return View(pais);
        }

        // POST: Paises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pais = await _context.Pais.FindAsync(id);
            _context.Pais.Remove(pais);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaisExists(int id)
        {
            return _context.Pais.Any(e => e.ID == id);
        }
    }
}

asp.net/estudo02 - net-5/10 - asp-net-entity-PartialView/src/ApplicationMVC/Controllers/TestesController.cs
using ApplicationInfra;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ApplicationMVC.Controllers
{
    public class TestesController : Controller
    {
        private readonly Contexto _context;
        public TestesController(Contexto context)
        {
            _context = context;

        }

        public IActionResult Index()
        {
            //ViewBag.Qtde = new LogBusiness().Maximo();

            return View();
        }
        [HttpGet]
        public PartialViewResult Listagem(string texto)
        {
            //faz a pesquisa
            var list = _context.Banco.Where(s => s.Codigo.Contains(texto)).OrderBy(s => s.Codigo).ToList();

            //faz o log
            //new LogBusiness().Registrar(Request.UserHostAddress, texto);

            return PartialView("_Listagem", list);
        }
        [HttpGet]
        public ActionResult Details(string id)
        {
            //var evento = new EventoBusiness().Buscar(id);
            var list = _context.Banco.Find(id);

            return View(list);
        }
    }
}

asp.net/estudo02 - net-5/10 - asp-net-entity-PartialView/src/ApplicationMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ApplicationMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        @{
             await Html.RenderPartialAsync("_MenuPartialView");
        }
    </header>
    <div id="MainContainer" class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ApplicationMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

asp.net/estudo02 - net-5/10 - asp-net-entity-PartialView/src/ApplicationMVC/Views/Shared/_MenuPartialView.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">

        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WEBAPP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">

                <!--CADASTROS-->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Cadastros
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        <div class="dropdown-divider"></div>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Bancos" asp-action="Listagem">Bancos</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Classes" asp-action="Index">Classes</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contato Tel.</a>
                        <div class="dropdown-divider"></div>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Testes" asp-action="Index">Partial Views</a>
                    </div>
                </li>
                <!--===============================================================================================-->
                <!--PARAMETROS-->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Parâmetros
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Paises" asp-action="Index">Países</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Estados" asp-action="Index">Estados</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Municipios" asp-action="Index">Municípios</a>
                        <div class="dropdown-divider"></div>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuários</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="LoginPage">Login</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="LogoffPage">Logoff</a>
                    </div>
                </li>
                <!--===============================================================================================-->

            </ul>
        </div>
    </div>
</nav>