asp.net/estudo02 - net-5/06 - asp-net-entity-Ordena-Lista/src/Web/Controllers/BancosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApplicationBusiness.CadastrosModels;
using ApplicationInfra;

namespace Web.Controllers
{
    public class BancosController : Controller
    {
        private readonly Contexto _context;

        public BancosController(Contexto context)
        {
            _context = context;
        }

        // GET: Bancos
        public async Task<IActionResult> Index(string OrdenaParm)
        {
            ViewBag.CodigoOrdenaParm = "codigo";
            ViewBag.NameOrdenaParm = "nome";
            ViewBag.FantasiaOrdenaParm = "fantasia";

            List<Banco> banco;

            switch (OrdenaParm)
            {
                case "codigo":
                    banco = await _context.Banco.OrderBy(s => s.Codigo).ToListAsync();
                    break;
                case "nome":
                    banco = await _context.Banco.OrderBy(s => s.Nome).ToListAsync();
                    break;
                case "fantasia":
                    banco = await _context.Banco.OrderBy(s => s.Fantasia).ToListAsync();
                    break;
                default:
                    banco = await _context.Banco.OrderBy(s => s.Nome).ToListAsync();
                    break;
            }

            return View(banco);
        }

        // GET: Bancos/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var banco = await _context.Banco
                .FirstOrDefaultAsync(m => m.Codigo == id);
            if (banco == null)
            {
                return NotFound();
            }

            return View(banco);
        }

        // GET: Bancos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Bancos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Codigo,Nome,Fantasia,IdEmpresa")] Banco banco)
        {
            if (ModelState.IsValid)
            {
                _context.Add(banco);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(banco);
        }

        // GET: Bancos/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var banco = await _context.Banco.FindAsync(id);
            if (banco == null)
            {
                return NotFound();
            }
            return View(banco);
        }

        // POST: Bancos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Codigo,Nome,Fantasia,IdEmpresa")] Banco banco)
        {
            if (id != banco.Codigo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(banco);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BancoExists(banco.Codigo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(banco);
        }

        // GET: Bancos/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var banco = await _context.Banco
                .FirstOrDefaultAsync(m => m.Codigo == id);
            if (banco == null)
            {
                return NotFound();
            }

            return View(banco);
        }

        // POST: Bancos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var banco = await _context.Banco.FindAsync(id);
            _context.Banco.Remove(banco);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BancoExists(string id)
        {
            return _context.Banco.Any(e => e.Codigo == id);
        }
    }
}

asp.net/estudo02 - net-5/06 - asp-net-entity-Ordena-Lista/src/Web/Views/Bancos/Create.cshtml
@model ApplicationBusiness.CadastrosModels.Banco

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Banco</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fantasia" class="control-label"></label>
                <input asp-for="Fantasia" class="form-control" />
                <span asp-validation-for="Fantasia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdEmpresa" class="control-label"></label>
                <input asp-for="IdEmpresa" class="form-control" />
                <span asp-validation-for="IdEmpresa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

asp.net/estudo02 - net-5/06 - asp-net-entity-Ordena-Lista/src/Web/Views/Bancos/Delete.cshtml
@model ApplicationBusiness.CadastrosModels.Banco

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Banco</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fantasia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fantasia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEmpresa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEmpresa)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Codigo" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

asp.net/estudo02 - net-5/06 - asp-net-entity-Ordena-Lista/src/Web/Views/Bancos/Details.cshtml
@model ApplicationBusiness.CadastrosModels.Banco

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Banco</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fantasia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fantasia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEmpresa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEmpresa)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Codigo">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

asp.net/estudo02 - net-5/06 - asp-net-entity-Ordena-Lista/src/Web/Views/Bancos/Edit.cshtml
@model ApplicationBusiness.CadastrosModels.Banco

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Banco</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Codigo" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fantasia" class="control-label"></label>
                <input asp-for="Fantasia" class="form-control" />
                <span asp-validation-for="Fantasia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdEmpresa" class="control-label"></label>
                <input asp-for="IdEmpresa" class="form-control" />
                <span asp-validation-for="IdEmpresa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

asp.net/estudo02 - net-5/06 - asp-net-entity-Ordena-Lista/src/Web/Views/Bancos/Index.cshtml
@model IEnumerable<ApplicationBusiness.CadastrosModels.Banco>

@{
    ViewData["Title"] = "Index";
    ApplicationBusiness.CadastrosModels.Banco firstDados = Model.ToList().FirstOrDefault();
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                
                <a asp-area="" asp-controller="Bancos" asp-action="Index" asp-route-OrdenaParm=@ViewBag.CodigoOrdenaParm>
                    <label asp-for="@firstDados.Codigo"></label>
                </a>

            </th>
            <th>

                <a asp-area="" asp-controller="Bancos" asp-action="Index" asp-route-OrdenaParm=@ViewBag.NomeOrdenaParm>
                    <label asp-for="@firstDados.Nome"></label>
                </a>

                
            </th>
            <th>

                <a asp-area="" asp-controller="Bancos" asp-action="Index" asp-route-OrdenaParm=@ViewBag.FantasiaOrdenaParm>
                    <label asp-for="@firstDados.Fantasia"></label>
                </a>

                
            </th>
            <th>
                
                <label asp-for="@firstDados.IdEmpresa"></label>                
                
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fantasia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdEmpresa)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Codigo">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Codigo">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Codigo">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>